#!/bin/sh

### BEGIN INIT INFO
# Provides:        RLOG
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Start real time logging daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

. /lib/lsb/init-functions

DAEMON=/root/realtime_logging.sh
PIDFILE=/var/run/realtime_logging.pid

case $1 in
	start)
		log_daemon_msg "Starting real time logging" "RLOG"
		start-stop-daemon --start --background --quiet --oknodo --pidfile $PIDFILE --make-pidfile --startas $DAEMON -- -p $PIDFILE
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping real time logging" "RLOG"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "Real time logging service"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
